brew install ack
brew install node
brew install zsh
brew install aspell
brew install git
brew install git-lfs
brew install terraform
brew install pyenv
brew install pyenv-virtualenv
brew install ykman
brew install make
brew install gpg
